name: cicd

on:  
    push:
      branches:
        - master

jobs:
    health-check-job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v2
    deploy-job:
        runs-on: ubuntu-latest
        steps:
          - name: Update code
            run: git pull
