# name of out worflow
name : Django CI/CD Workflow

# triggers for our worflow
on:
	# opening a pull request to master and develop branch will be a trigger
	pull_request:
		branches:
			- master

# three job definition
jobs:
	health-check-job: # health check job for testing and code formatting check
		runs-on: ubuntu-latest # os for running the job
		steps:
		  - name: Checkout code # checking our code at current commit that triggers the workflow
		  uses: actions/checkout@v2
	deploy-job: # deploy job is for deploying our code to azure vm
		runs-on: ubuntu-latest
		steps:
		  - name: Code Update 
		    id: update
		    run: git pull
		  - name: Copy config
		    id: copy
		    run: sudo cp -f /srv/zist-hol/.config/nginx/mysite.conf /etc/nginx/sites-available/mysite.conf
		  - name: Link config
		    id: link
		    run: sudo ln -sf /etc/nginx/sites-available/mysite.conf /etx/nginx/sites-enabled/mysite.conf
		  - name: Reload daemon
		    id: reload
		    run: sudo systemctl daemon-reload
		  - name: Restart Service
		    id: restart
		    run: sudo systemctl restart uwsgi nginx
